<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <path d="M7 14h3v3H7zm4 0h3v3h-3zm4 0h3v3h-3zm4 0h3v3h-3zM11 18h3v3h-3zm4 0h3v3h-3zm4 0h4c1.8 0 3.1-.5 4-1.5" fill="none" stroke="#7CC1FF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M24.5 12.2c.8-.8 1.6-.9 2.5-.7-.1 1-.5 1.8-1.3 2.4" fill="none" stroke="#7CC1FF" stroke-width="2" stroke-linecap="round"/>
</svg>
