<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <path d="M7 24V9l5 7 4-5 4 5 5-7v15" fill="none" stroke="#7AA2F7" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
